name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name to build (e.g. v1.0.0). Required for manual runs.'
        required: true

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            platform: linux
          - os: macos-latest
            arch: arm64
            platform: macos
          - os: windows-latest
            arch: x64
            platform: windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref }}
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Setup dependencies (Ubuntu)
        if: matrix.platform == 'linux'
        run: |
          ./setup-linux.sh

      - name: Setup dependencies (macOS)
        if: matrix.platform == 'macos'
        run: |
          ./setup-macos.sh

      - name: Setup MSVC (Windows)
        if: matrix.platform == 'windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup dependencies (Windows)
        if: matrix.platform == 'windows'
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
          .\setup-windows.ps1

      - name: Build project
        shell: bash
        run: |
          ./run.sh

      - name: List build artifacts
        shell: bash
        run: |
          echo "=== Build directory contents ==="
          find build/bin -type f 2>/dev/null || echo "No build/bin directory"
          echo ""
          echo "=== All directories ==="
          find build -maxdepth 2 -type d 2>/dev/null || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yakety-${{ matrix.platform }}-${{ matrix.arch }}-${{ github.run_id }}
          path: |
            build/bin/*
            !build/bin/CMakeFiles
          retention-days: 7

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: Organize artifacts
        shell: bash
        run: |
          mkdir -p release-assets
          echo "=== All downloaded artifacts ==="
          find all-artifacts -type f
          echo ""
          echo "=== Organizing files ==="
          # Copy all binaries to release-assets, preserving platform info
          find all-artifacts -type f ! -name ".gitkeep" ! -path "*/CMakeFiles/*" -exec cp {} release-assets/ \;
          echo "=== Release assets ==="
          ls -la release-assets/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
          artifacts: "release-assets/*"
          allowUpdates: true
          replacesArtifacts: true
          draft: false
          prerelease: false
